version: '3.4'

services:
  web:
    environment:
      - CONTRAST__SERVER__NAME=RailsGoat-container-qa
      - CONTRAST__SERVER__ENVIRONMENT=qa 
      - CONTRAST__ASSESS__ENABLE=true
      - CONTRAST__PROTECT__ENABLE=false
